services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4242:4200
    command: npm start:client
    depends_on:
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start:api
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
