name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package.lock.json') }}
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx format:check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package.lock.json') }}
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx affected --target=lint --parallel=3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package.lock.json') }}
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx affected --target=test --parallel=3 --configuration=ci
